let a = 4;
let b = 5;
let c = a + b;
console.log(c);
let d = 30;
let e = 3;
let f = d - e;
console.log(f);
var gh = 4;
var hg = 5;
var hi = gh * hg;
console.log(hi);
let abc = 20;
let bca = 10;
let cba = abc / bca;
console.log(cba);
let sr = 50;
let sree = 20;
let sreeks = sr % sree;
console.log(sreeks);
let power = 10;
let s = 3;
let powerof = power ** s;
console.log(powerof);